### ISSUE TITLE
question of "VO+imu"

### ISSUE THREAD

**Issue by Sprann9257** [meyiao/SimpleStereoVO#3]
HI，i'm very interest in the result of "VO+imu", could you share  your code of loosely coupled visual odometry, or share me same reference code. Thx！！

**Comment by meyiao** [comment]
Hi, there is no imu information in the KITTI dataset, I just add some noise(3 degrees) to ground truth to simulate the fused imu orientation! Then replace the rotation angles in the VO results! And compute the trajectory!
